### ISSUE TITLE
可以提供更多的参数设置么

### ISSUE THREAD

**Issue by wwqgtxx** [koolshare/merlin_frpc#2]
比如`heartbeat_interval`和`heartbeat_timeout`这两个参数很重要，如果服务器和客户端的无法匹配就会导致连接被反复断开

另外，frpc新版本提供了socks5/http代理,配置参数在[https://github.com/fatedier/frp/blob/master/README_zh.md#通过-frpc-所在机器访问外网](https://github.com/fatedier/frp/blob/master/README_zh.md#通过-frpc-所在机器访问外网)
以及[stcp功能](https://github.com/fatedier/frp/blob/master/README_zh.md#安全地暴露内网服务)
能不能在设置界面上也提供这些功能的设置呢，如果添加起来麻烦也可以提供一个单独的页面让用户直接手动修改frpc.ini这样方便有特殊需求的用户使用

**Comment by clangcn** [comment]
有空准备干掉这个界面了，重新弄一个设置页面，只有一个文本框，所有配置内容写完填进去。
