### ISSUE TITLE
梅林系统中没有start-stop-daemon 这个软件，插件执行不成功

### ISSUE THREAD

**Issue by victsww** [koolshare/merlin_frpc#3]
梅林系统中没有start-stop-daemon 这个软件
frpc/scripts/config-frpc.sh中的“start-stop-daemon -S -q -b -m -p ${PID_FILE} -x ${BIN} -- -c ${INI_FILE}”这条命令执行不成功，如何解决，或者请问如何安装start-stop-daemon 这个软件

**Comment by clangcn** [comment]
本插件是基于Koolshare定制的梅林固件开发，其他平台我不是很清楚。
