### ISSUE TITLE
2.1.9的插件装上以后显示进程未运行。

### ISSUE THREAD

**Issue by zhurifx** [koolshare/merlin_frpc#5]
ac88u  7.4版本显示进程未运行，升级到7.7还是这样，jffs也格式化了，也恢复出厂设置了，服务器端也升级到0.16版本了，不管怎么提交进程就是不运行啊。原先用的一直好好的，没出过问题。

**Comment by zhurifx** [comment]
连接设置选择失败后退出程序运行成功了，选择重复连接就不行

**Comment by cocozq** [comment]
R8000梅林7.7也出现了同样的问题
